version: '3.8'
services:
  # frontend:
  #   container_name: client
  #   build: ./client
  #   volumes:
  #     - './:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   command: npm start
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  # prisma-postgres-api:
  #   stdin_open: true
  #   build:
  #     context: server/
  #     dockerfile: Dockerfile
  #   container_name: prisma-postgres-api
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "4000:4000"
  #   restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
volumes:
  postgres-data:
  pgadmin-data: